#[deviceID]
# 音声デバイスのUID
#UID_1 = AppleUSBAudioEngine:Generic:TX 384kb Hifi Type_C Audio:201701110001:1
#UID_2 = AppleUSBAudioEngine:Audient:Audient iD14:1120000:1,2
#UID_1 = BuiltInHeadphoneOutputDevice
#UID_2 = BuiltInSpeakerDevice

#UID_1 = AppleUSBAudioEngine:Focusrite:Scarlett Solo USB:Y7QPRR9191C0F1:1,2
#UID_2 = AppleUSBAudioEngine:Generic:TX 384kb Hifi Type_C Audio:201701110001:1

# 当日は通知音が会場にいかないように、システムデフォルトをmacbookのスピーカーにし、音量0にすること。
# 再生開始以降はマウスオフ

# ここより上は使われない 


[SeekPoints]
# シークポイントのリスト (番号="タイトル"=hh:mm:ss:fr)
# ※ fr は 60fps におけるフレーム数 (0〜59)
01 = "Opening"=00:00:00:00
02 = "A_band"=00:02:40:00
03 = "B_band"=00:15:20:00
04 = "C_band"=00:34:20:00
05 = "additional"=00:52:13:41