# ========================================
# プレイヤー設定
# screen_index: 0=メイン, 1=外部1, 2=外部2 ...（get_device_ids.pyで確認した番号）
# ========================================
[Player_1]
file = 202606学祭_下画面_会場音声.mov
screen_index = 2
audio_uid = AppleUSBAudioEngine:Focusrite:Scarlett Solo USB:Y7QPRR9191C0F1:1,2

[Player_2]
file = 202606学祭_上画面_ヘッド音声.mov
screen_index = 1
audio_uid = AppleUSBAudioEngine:Qualcomm Technologies Inc.:USB Audio Device:1110000:1

# 3つ目の画面が必要な場合は以下のコメントアウトを外して設定
# [Player_3]
# file = file3.mov
# screen_index = 2
# audio_uid = 

# ========================================
# シークポイント設定
# ========================================
[SeekPoints]
# シークポイントのリスト (番号="タイトル"=hh:mm:ss:fr)
# ※ fr は 60fps におけるフレーム数 (0〜59)
01 = "Opening"=00:00:00:00
02 = "1_"=00:03:43:00
03 = "2_"=00:06:09:00
04 = "3_"=00:09:24:00
05 = "4_"=00:12:04:00
06 = "5_"=00:17:13:00
07 = "6_"=00:20:42:00
08 = "7_"=00:26:52:00
09 = "8_"=00:30:23:00
10 = "9_"=00:35:39:00
11 = "10_"=00:42:15:00
12 = "11_"=00:47:00:00
13 = "12_"=00:51:03:00